# Generated by Django 3.0.3 on 2020-11-26 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BwContentSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DateTimeField()),
                ('blogs', models.IntegerField(default=0, verbose_name='Blogs')),
                ('twitter', models.IntegerField(default=0, verbose_name='Twitter')),
                ('reddit', models.IntegerField(default=0, verbose_name='Reddit')),
            ],
        ),
        migrations.CreateModel(
            name='BwEmotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DateTimeField()),
                ('anger', models.IntegerField(default=0, verbose_name='Anger')),
                ('fear', models.IntegerField(default=0, verbose_name='Fear')),
                ('disgust', models.IntegerField(default=0, verbose_name='Disgust')),
                ('joy', models.IntegerField(default=0, verbose_name='Fear')),
                ('surprise', models.IntegerField(default=0, verbose_name='Surprise')),
                ('sadness', models.IntegerField(default=0, verbose_name='Sadness')),
            ],
        ),
        migrations.CreateModel(
            name='BwGeography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.CharField(max_length=100)),
                ('hibcat_monitor', models.IntegerField(verbose_name='HIBCAT Monitor')),
            ],
        ),
        migrations.CreateModel(
            name='BwNetSentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DateTimeField()),
                ('hibcat_monitor', models.FloatField(verbose_name='HIBCAT Monitor')),
            ],
        ),
        migrations.CreateModel(
            name='BwSentiments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DateTimeField()),
                ('positive', models.IntegerField(default=0)),
                ('neutral', models.IntegerField(default=0)),
                ('negative', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BwVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DateTimeField()),
                ('hibcat_monitor', models.IntegerField(verbose_name='HIBCAT Monitor')),
            ],
        ),
        migrations.CreateModel(
            name='ClineCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateTimeField()),
                ('article_id', models.CharField(max_length=100, verbose_name='_id')),
                ('aid', models.IntegerField()),
                ('source_name', models.CharField(max_length=100)),
                ('source_location', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('title', models.TextField()),
                ('source_host', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('pronouns', models.IntegerField()),
                ('other_metadata', models.TextField()),
                ('original_language', models.CharField(max_length=100)),
                ('mf_harmvirtue', models.FloatField()),
                ('mf_purityvirtue', models.FloatField()),
                ('mf_purityvice', models.FloatField()),
                ('mf_moralitygeneral', models.FloatField()),
                ('mf_ingroupvirtue', models.FloatField()),
                ('mf_ingroupvice', models.FloatField()),
                ('mf_harmvice', models.FloatField()),
                ('mf_fairnessvice', models.FloatField()),
                ('mf_fairnessvirtue', models.FloatField()),
                ('mf_authorityvirtue', models.FloatField()),
                ('mf_authorityvice', models.FloatField()),
                ('dal_activation', models.FloatField()),
                ('dal_pleasantness', models.FloatField()),
                ('dal_imagery', models.FloatField()),
                ('lexicoder_pos', models.FloatField()),
                ('lexicoder_neg', models.FloatField()),
                ('inquirer_pos', models.FloatField()),
                ('inquirer_neg', models.FloatField()),
                ('bing_liu_neg', models.FloatField()),
                ('bing_liu_pos', models.FloatField()),
                ('anew_valence', models.FloatField()),
                ('anew_arousal', models.FloatField()),
                ('anew_dominance', models.FloatField()),
                ('offset', models.FloatField()),
                ('geolocation_probabilities', models.TextField()),
                ('geolocation', models.TextField()),
                ('geolocation_featureids', models.TextField()),
                ('geolocation_original', models.TextField()),
                ('extracted_organizations', models.TextField()),
                ('geolocation_locations', models.TextField()),
                ('extracted_people', models.TextField()),
                ('extracted_locations', models.TextField()),
                ('country', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DateTimeField()),
                ('male', models.IntegerField(default=0)),
                ('female', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='YahooStockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('open', models.FloatField(verbose_name='Open')),
                ('high', models.FloatField(verbose_name='High')),
                ('low', models.FloatField(verbose_name='Low')),
                ('close', models.FloatField(verbose_name='Close')),
                ('adj_close', models.FloatField(verbose_name='Adj Close')),
            ],
        ),
        migrations.CreateModel(
            name='ShortInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_volume', models.IntegerField()),
                ('total_volume', models.IntegerField()),
                ('short_volume_ratio', models.FloatField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shortinterests', to='ibhi.YahooStockData')),
            ],
        ),
    ]
