# Generated by Django 3.0.3 on 2020-12-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibhi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinecenter',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
