# Generated by Django 3.0.3 on 2020-11-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibhi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bwcontentsources',
            name='blogs',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Blogs'),
        ),
        migrations.AlterField(
            model_name='bwcontentsources',
            name='days',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bwcontentsources',
            name='reddit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Reddit'),
        ),
        migrations.AlterField(
            model_name='bwcontentsources',
            name='twitter',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='bwemotions',
            name='anger',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Anger'),
        ),
        migrations.AlterField(
            model_name='bwemotions',
            name='days',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bwemotions',
            name='disgust',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Disgust'),
        ),
        migrations.AlterField(
            model_name='bwemotions',
            name='fear',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Fear'),
        ),
        migrations.AlterField(
            model_name='bwemotions',
            name='joy',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Fear'),
        ),
        migrations.AlterField(
            model_name='bwemotions',
            name='sadness',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sadness'),
        ),
        migrations.AlterField(
            model_name='bwemotions',
            name='surprise',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Surprise'),
        ),
        migrations.AlterField(
            model_name='bwgeography',
            name='countries',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bwgeography',
            name='hibcat_monitor',
            field=models.IntegerField(blank=True, null=True, verbose_name='HIBCAT Monitor'),
        ),
        migrations.AlterField(
            model_name='bwnetsentiment',
            name='days',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bwnetsentiment',
            name='hibcat_monitor',
            field=models.FloatField(blank=True, null=True, verbose_name='HIBCAT Monitor'),
        ),
        migrations.AlterField(
            model_name='bwsentiments',
            name='days',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bwsentiments',
            name='negative',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bwsentiments',
            name='neutral',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bwsentiments',
            name='positive',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bwvolume',
            name='days',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bwvolume',
            name='hibcat_monitor',
            field=models.IntegerField(blank=True, null=True, verbose_name='HIBCAT Monitor'),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='aid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='anew_arousal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='anew_dominance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='anew_valence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='article_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='_id'),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='bing_liu_neg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='bing_liu_pos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='dal_activation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='dal_imagery',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='dal_pleasantness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='extracted_locations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='extracted_organizations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='extracted_people',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='geolocation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='geolocation_featureids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='geolocation_locations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='geolocation_original',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='geolocation_probabilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='inquirer_neg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='inquirer_pos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='lexicoder_neg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='lexicoder_pos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='mf_authorityvice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='mf_authorityvirtue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='mf_fairnessvice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='mf_fairnessvirtue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='mf_harmvice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='mf_harmvirtue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='mf_ingroupvice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='mf_ingroupvirtue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='mf_moralitygeneral',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='mf_purityvice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='mf_purityvirtue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='offset',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='original_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='other_metadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='pronouns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='source_host',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='source_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='source_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='days',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='female',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='male',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shortinterest',
            name='short_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shortinterest',
            name='short_volume_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shortinterest',
            name='total_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yahoostockdata',
            name='adj_close',
            field=models.FloatField(blank=True, null=True, verbose_name='Adj Close'),
        ),
        migrations.AlterField(
            model_name='yahoostockdata',
            name='close',
            field=models.FloatField(blank=True, null=True, verbose_name='Close'),
        ),
        migrations.AlterField(
            model_name='yahoostockdata',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='yahoostockdata',
            name='high',
            field=models.FloatField(blank=True, null=True, verbose_name='High'),
        ),
        migrations.AlterField(
            model_name='yahoostockdata',
            name='low',
            field=models.FloatField(blank=True, null=True, verbose_name='Low'),
        ),
        migrations.AlterField(
            model_name='yahoostockdata',
            name='open',
            field=models.FloatField(blank=True, null=True, verbose_name='Open'),
        ),
    ]
