# Generated by Django 3.1.5 on 2021-01-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibhi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinecenter',
            name='publication_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
