# Generated by Django 3.0.3 on 2020-12-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibhi', '0002_auto_20201210_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinecenter',
            name='aid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
