# Generated by Django 3.0.3 on 2020-12-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibhi', '0003_auto_20201211_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinecenter',
            name='article_id',
            field=models.TextField(blank=True, null=True, verbose_name='_id'),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='original_language',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='publisher',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='source_host',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='source_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='source_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
