# Generated by Django 3.1.5 on 2021-01-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibhi', '0003_auto_20210117_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinecenter',
            name='publication_date_only',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinecenter',
            name='publication_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinecenter',
            name='publication_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
