# Generated by Django 3.1.5 on 2021-02-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibhi', '0004_auto_20210117_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCEventTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name="Event's Start Date")),
                ('end_date', models.DateField(blank=True, null=True, verbose_name="Event's End Date")),
                ('event_type', models.CharField(choices=[('Positive Shock - Planned Activity', 'Positive Shock - Planned Activity'), ('Positive Shock - Unplanned Activity', 'Positive Shock - Unplanned Activity'), ('Negative Shock - Planned Activity', 'Negative Shock - Planned Activity'), ('Negative Shock - Unplanned Activity', 'Negative Shock - Unplanned Activity')], default='Positive Shock - Planned Activity', max_length=50, verbose_name='Event Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Event Description')),
            ],
        ),
    ]
