# Generated by Django 3.0.3 on 2021-01-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibhi', '0005_auto_20201211_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='BwActivityDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfWeek', models.IntegerField(blank=True, null=True)),
                ('day_vol', models.BigIntegerField(blank=True, null=True, verbose_name='Day Volume')),
            ],
        ),
        migrations.CreateModel(
            name='BwActivityTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourOfDay', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('time_vol', models.BigIntegerField(blank=True, null=True, verbose_name='Timely Volume')),
            ],
        ),
        migrations.RemoveField(
            model_name='bwgeography',
            name='hibcat_monitor',
        ),
        migrations.RemoveField(
            model_name='bwnetsentiment',
            name='hibcat_monitor',
        ),
        migrations.RemoveField(
            model_name='bwvolume',
            name='hibcat_monitor',
        ),
        migrations.AddField(
            model_name='bwgeography',
            name='geo_vol',
            field=models.IntegerField(blank=True, null=True, verbose_name='Geographic Volume'),
        ),
        migrations.AddField(
            model_name='bwnetsentiment',
            name='net_sent_vol',
            field=models.FloatField(blank=True, null=True, verbose_name='Net Sentiment Volume'),
        ),
        migrations.AddField(
            model_name='bwvolume',
            name='volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Activity Volume'),
        ),
    ]
