# Generated by Django 3.1.5 on 2021-02-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibhi', '0005_cceventtimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='bwsentiments',
            name='net_sentiment',
            field=models.FloatField(blank=True, null=True, verbose_name='Net Sentiment'),
        ),
        migrations.AddField(
            model_name='clinecenter',
            name='bing_liu_net_sentiment',
            field=models.FloatField(blank=True, null=True, verbose_name='Bing Liu Net Sentiment'),
        ),
    ]
