# Generated by Django 3.1.5 on 2021-02-13 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibhi', '0006_auto_20210213_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinecenter',
            name='bing_liu_net_sentiment',
        ),
    ]
