# Generated by Django 3.1.5 on 2021-02-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibhi', '0008_clinecenter_bing_liu_net_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bwsentiments',
            name='volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Volume (Pos+Neg)'),
        ),
    ]
