# Generated by Django 3.1.5 on 2021-02-14 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibhi', '0009_bwsentiments_volume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cceventtimeline',
            old_name='start_date',
            new_name='date',
        ),
    ]
