# Generated by Django 3.1.5 on 2021-04-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibhi', '0010_auto_20210214_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='bwactivityday',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bwactivitytime',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bwcontentsources',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bwemotions',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bwgeography',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bwnetsentiment',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bwsentiments',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bwvolume',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cceventtimeline',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinecenter',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gender',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shortinterest',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yahoostockdata',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
    ]
