# Generated by Django 3.1.5 on 2021-05-03 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibhi', '0002_auto_20210426_1539'),
        ('ibhi', '0011_auto_20210425_1153'),
    ]

    operations = [
    ]
